### ISSUE TITLE
State control

### ISSUE THREAD

**Issue by dy** [dfcreative/prama#7]
As suggested by @rreusser https://github.com/freeman-lab/control-panel/pull/13#issuecomment-231604545, state control may be of use:

``` js
panel.next();
panel.prev();
panel.save('name');
panel.load('name');
```

That seems to be the case of dat.gui btw.

**Comment by rreusser** [comment]
Interesting. I'm realizing that I effectively suggested a full undo-redo feature, which seems (IMO) a bit heavy. `prama.on('change', …);` together with `.get` and `.set` is probably all you need to fairy easily add undo/redo yourself. The pain point for me with `control-panel` is that events give you the whole state and I never got around to adding field names to the event or just diffing it and isolating the changes. So if I were to use prama I'd be 100% satisfied with `prama.on('change', (name, value, opts) => {});` as you've defined it. 👍

**Comment by dy** [comment]
Done)
